version: '3.8'

services:
  app:
    build:
      context: .
      no_cache: true
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=ankitdesai
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ad-agent
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./utils/setup_test_data.sql:/docker-entrypoint-initdb.d/setup_test_data.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: 